### ISSUE TITLE
docker-compose를 추가하라

### ISSUE THREAD

**Issue by audtjddld** [audtjddld/spring-crawler-sample#8]
```
version: '3.6'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.12-2.5.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_CREATE_TOPICS: "test:1:1"

```
